# Generated by Django 4.2.6 on 2023-10-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
